import DocumentProvider    from "@app/_components/document/DocumentProvider.jsx";
import { KRDS_FONT } from "@app/_components/_font/FontContainer.js";
import "./globals.css";
import MapCompass          from "@components/cesium/compass/MapCompass.jsx";

export const metadata = {
	title      : "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<DocumentProvider>
			<body className={KRDS_FONT.REGULAR.className}>
			{children}
			<MapCompass />
			</body>
		</DocumentProvider>
	);
}
