import { KRDS_FONT }    from "@app/_components/_font/FontContainer.js";
import "./globals.css";
import DocumentProvider from "@app/_components/document/DocumentProvider.jsx";

export const metadata = {
	title      : "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<DocumentProvider>
			<body className={KRDS_FONT.REGULAR.className}>
			{children}
			</body>
		</DocumentProvider>
	);
}
